name: Run tests

on: [push]

jobs:
  unittest:
    name: Run unit tests with unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Run unittest
        run: python -m unittest test_main_unit.py
  
  pytest:
    name: Run tests with pytest
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest test_main_pytest.py -v
